services:
  computervision-service:
    build:
      context: computervision-service
      dockerfile: Dockerfile.${PROCESSING_TYPE}
    ports:
      - "50051:50051"
    networks:
      - backend-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: ${NUM_GPUS:-0}
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend-network
    command: mongod --bind_ip_all
    volumes:
      - mongo-data:/data/db
  go-server:
    build:
      context: server/go-server
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      COMPUTER_VISION_URI: "computervision-service:50051"
    networks:
      - backend-network
      - frontend-network
    depends_on:
      mongodb:
        condition: service_started
      computervision-service:
        condition: service_started

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
